services:
  db:
    image: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file:
      - ./backend/.env.development
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env.development
volumes:
  db-volume:
