name: CI

on:
  push:
    branches: [develop]

jobs:
  front-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repositry
        uses: actions/checkout@v4

      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: 23.7.0

      - name: install yarn
        run: yarn install
        working-directory: frontend
      
      - name: eslint check
        run: yarn eslint
        working-directory: frontend

      - name: build check
        env:
          DISABLE_ESLINT_PLUGIN: true
        run: yarn build
        working-directory: frontend

  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repositry
        uses: actions/checkout@v4
      
      - name: set up ruby
        uses: ruby/setup-ruby@v1 
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: bundler and gem install
        run: |
          gem install bundler
          bundle install
        working-directory: backend
      
      - name: run rubocop
        run: bundle exec rubocop
        working-directory: backend